# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "uas" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/aece897d-f9a2-4b63-acad-28b906761e19";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/387A-5B1E";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  # fileSystems."/run/media/h4rl/home-server" = {
  #   device = "h4rl@192.168.1.77:/home/h4rl/";
  #   fsType = "sshfs";
  #   options = [
  #     "IdentityFile=/home/h4rl/.ssh/h4rl-nisemono"
  #     "Port=22345"
  #     "nodev"
  #     "noatime"
  #     "allow_other"
  #   ];
  # };

  zramSwap = {
    enable = true;
    memoryPercent = 50;
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
